version: '3.7'

services:
  mariadb-master:
    image: 'bitnami/mariadb:10.1.29-r2'
    ports:
    - 3306:3306
    environment:
    - MARIADB_REPLICATION_MODE=master
    - MARIADB_REPLICATION_USER=replication_user
    - MARIADB_REPLICATION_PASSWORD=replication_password
    - MARIADB_ROOT_PASSWORD=mariadb_root_password
    volumes:
    - /opt/data:/bitnami/mariadb
    deploy:
      placement:
        constraints:
          - node.hostname==docker_master_hostname
  mariadb-slave:
    image: 'bitnami/mariadb:10.1.29-r2'
    ports:
    - 3307:3306
    environment:
    - MARIADB_REPLICATION_MODE=slave
    - MARIADB_REPLICATION_USER=replication_user
    - MARIADB_REPLICATION_PASSWORD=replication_password
    - MARIADB_MASTER_HOST=mariadb_master_host
    - MARIADB_MASTER_ROOT_PASSWORD=mariadb_root_password
    volumes:
    - /opt/data:/bitnami/mariadb
    deploy:
      placement:
        constraints:
          - node.hostname==docker_slave_hostname


