version: '3.7'

services:
  mariadb-master:
    image: 'bitnami/mariadb:10.1.29-r2'
    ports:
    - 3306:3306
    environment:
    - MARIADB_REPLICATION_MODE=master
    - MARIADB_REPLICATION_USER=repl
    - MARIADB_REPLICATION_PASSWORD=repl12345
    - MARIADB_ROOT_PASSWORD=test12345
    deploy:
      placement:
        constraints:
          - node.hostname==docker_master_hostname
  mariadb-slave:
    image: 'bitnami/mariadb:10.1.29-r2'
    ports:
    - 3307:3306
    environment:
    - MARIADB_REPLICATION_MODE=master
    - MARIADB_REPLICATION_USER=repl
    - MARIADB_REPLICATION_PASSWORD=repl12345
    - MARIADB_MASTER_HOST=mariadb-master
    - MARIADB_MASTER_ROOT_PASSWORD=test12345
    deploy:
      placement:
        constraints:
          - node.hostname==docker_slave_hostname


